name: Deploy Static CCF site (files nuxt generate)
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '27 0 * * *'

concurrency:
  group: Lerntherapie Freiburg Static Build
  cancel-in-progress: true    

jobs:
  # Build job
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: yarn
      - name: Static HTML export with Nuxt
        run: yarn generate
      - name: Upload to WebDAV
        uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{ secrets.WEBDAV_ADDRESS }}
          webdav_username: ${{ secrets.WEBDAV_USERNAME }}
          webdav_password: ${{ secrets.WEBDAV_PASSWORD }}
          webdav_upload_path: "/html"
          files: ".output/public/**"
          keep_structure: true
